### All consensus sequences generated

##----------------------------------------------------------------------------------------------------------
def reverse_sequence(sequence):
    reversed_sequence = ""
    for i in range(len(sequence)):
        base = sequence[-1-i].upper()

        if base == "A":
            new_base = "T"
        elif base == "C":
            new_base = "G"
        elif base == "G":
            new_base = "C"
        elif base == "T":
            new_base = "A"
        else:
            print("Error: can only reverse sequences consisting of A/C/G/T")
        reversed_sequence += new_base
    return(reversed_sequence)



all_consensuses = {}
##----------------------------------------------------------------------------------------------------------




## BATCH 1
##----------------------------------------------------------------------------------------------------------
## 20JK4316D long allele:
patient_20JK4316D_long_global = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAG
GCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCG
GCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCG
GCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCG
GCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGC""".replace("\n", "")
all_consensuses["20JK4316D_long_global"] = patient_20JK4316D_long_global

patient_20JK4316D_long_local = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGAGGCGGCGGCGGAG
GAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAG
GAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAG
GAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAG
GAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGC""".replace("\n", "")
all_consensuses["20JK4316D_long_local"] = patient_20JK4316D_long_local

patient_20JK4316D_long_flye = """GGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGAGGAGGCGGCGGCGGAGGA
GGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGA
GGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGCGGAGGAGGCGGCGGCGGA
GGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGAGGAGGAGGCGGCGGCG
GAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCG
GAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGC""".replace("\n", "")
all_consensuses["20JK4316D_long_flye"] = patient_20JK4316D_long_flye

patient_20JK4316D_long_garvan = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCg
cGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCG
GCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAgGGCG
GCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGCGGCGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGAGGAGGCGGC""".replace("\n", "")
all_consensuses["20JK4316D_long_garvan"] = patient_20JK4316D_long_garvan


## 20JK4316D short allele:
patient_20JK4316D_short_global = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGCGGGCGGCGGGGGCGG
C""".replace("\n", "")
all_consensuses["20JK4316D_short_global"] = patient_20JK4316D_short_global

patient_20JK4316D_short_local = """GGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGCGGGCGGCGGGGGCGGC""".replace("\n", "")
all_consensuses["20JK4316D_short_local"] = patient_20JK4316D_short_local

patient_20JK4316D_short_flye = """GGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGAGGAGGCGGC""".replace("\n", "")
all_consensuses["20JK4316D_short_flye"] = patient_20JK4316D_short_flye

patient_20JK4316D_short_garvan = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGAGGAGGCGGC"""
all_consensuses["20JK4316D_short_garvan"] = patient_20JK4316D_short_garvan


## 21LE9817N long allele:
patient_21LE9817N_long_global = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGAGGAGGCGGCGGCGG
AGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGG
AGGAGGCGGCGGCGGAGGAGGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAG
GAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAG
GAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGC""".replace("\n", "")
all_consensuses["21LE9817N_long_global"] = patient_21LE9817N_long_global

patient_21LE9817N_long_local = """GGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGG
CGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGG
CGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGG
CGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGG
CGGCGGAGGAGGCGGCGGCGGAGGAGGCGGC""".replace("\n", "")
all_consensuses["21LE9817N_long_local"] = patient_21LE9817N_long_local

patient_21LE9817N_long_flye = reverse_sequence("""GCCGC
CTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGC
CTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGC
CTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGC
CTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGC
CTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGC
CTCCTCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCC""".replace("\n", ""))
all_consensuses["21LE9817N_long_flye"] = patient_21LE9817N_long_flye

patient_21LE9817N_long_garvan = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGA
GGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCG
GAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGG
CGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCG""".replace("\n", "")
all_consensuses["21LE9817N_long_garvan"] = patient_21LE9817N_long_garvan


## 21LE9817N short allele:
patient_21LE9817N_short_global = """GGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGAGGAGGCGGC""".replace("\n", "")
all_consensuses["21LE9817N_short_global"] = patient_21LE9817N_short_global

patient_21LE9817N_short_local = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGAGGAGGCGGC""".replace("\n", "")
all_consensuses["21LE9817N_short_local"] = patient_21LE9817N_short_local

patient_21LE9817N_short_flye = reverse_sequence("""GCCGCCTCCTCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["21LE9817N_short_flye"] = patient_21LE9817N_short_flye

patient_21LE9817N_short_garvan = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGAGGAGGCGGCG""".replace("\n", "")
all_consensuses["21LE9817N_short_garvan"] = patient_21LE9817N_short_garvan


## 22NZ3355R long allele:
patient_22NZ3355R_long_global = reverse_sequence("""GC
CGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGC
CGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGC
CGCCTCCTCCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCACCCTCCCGC
CGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCGCCGCCGGCCACCGCCTCCGCCGCCGCCTCCTCCG
CCGCCGCCTCCTCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["22NZ3355R_long_global"] = patient_22NZ3355R_long_global

patient_22NZ3355R_long_local = reverse_sequence("""GC
CGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGC
CGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGC
CGCCTCCTCCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCACCCTCCCGC
CGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCGCCGCCGGCCACCGCCTCCGCCGCCGCCTCCTCCG
CCGCCGCCTCCTCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["22NZ3355R_long_local"] = patient_22NZ3355R_long_local

# Flye didn't work for this so no Flye allele

patient_22NZ3355R_long_garvan = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGagGcgGtgGcCGGCGGAGGAGGCGGCGGCGGA
GGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCG
GgAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCG
GCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGC""".replace("\n", "")
all_consensuses["22NZ3355R_long_garvan"] = patient_22NZ3355R_long_garvan


## 22NZ3355R short allele:
patient_22NZ3355R_short_global = reverse_sequence("""GC
CGCCTCCTCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["22NZ3355R_short_global"] = patient_22NZ3355R_short_global

patient_22NZ3355R_short_local = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGCGGCGGAGGAGGCGGC""".replace("\n", "")
all_consensuses["22NZ3355R_short_local"] = patient_22NZ3355R_short_local

patient_22NZ3355R_short_garvan = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GAGGAGGCGGC""".replace("\n", "")
all_consensuses["22NZ3355R_short_garvan"] = patient_22NZ3355R_short_garvan
##----------------------------------------------------------------------------------------------------------




## ISHIURA
##----------------------------------------------------------------------------------------------------------
## Ishiura F9193-II-5 corrected long allele:
ishiura_2019_f9193_ii_5_corrected_long_global = """GGCGGCGGCGGCG
GCGGCGGCGGCGGCGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGGCGGCGGCGGCGGCGGCGCGGCGGCGGCGGCGGCGGCGGCGGCGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGGCGGCGGCGGCGGCGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGGCGGCGGCG
GCGGCGGCGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC""".replace("\n", "")
all_consensuses["ishiura_2019_f9193_ii_5_corrected_long_global"] = ishiura_2019_f9193_ii_5_corrected_long_global

ishiura_2019_f9193_ii_5_corrected_long_local = """GGCGGCGGCGGCG
GCGGCGGCGGCGGCGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGCGGCGGCGGCGGCGGGCGGCGGCGGCGGGCGGCGGCGGCGGCGGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGGCGGCGGCGGGCGGCGGCGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGGGCGCGGCGGCGGCGGCGGCGGCGGCGGGGGCGGCGGCGGCG
GCGGCGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGGGCGGCGGGGGCGGCGGCGGCGGCGGCGGC""".replace("\n", "")
all_consensuses["ishiura_2019_f9193_ii_5_corrected_long_local"] = ishiura_2019_f9193_ii_5_corrected_long_local


## Ishiura F9193-II-5 raw long allele:
ishiura_2019_f9193_ii_5_raw_long_global = """GGCGGCGGCGGCG
GCGGCGGCCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGGGCGGCGGCGCGCGGCGGCGGCGGCGGCGGCGGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGGCGGCGGCGCGGCGCGGCGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGGGGGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGGGCGGCGGCGCGGCGGGGGCGGCGGGCGGCGGCGGCGG
CGGCGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCCGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGGGCGGCGGGCGGGGCGGCGCGGCGGCGGCGGC""".replace("\n", "")
all_consensuses["ishiura_2019_f9193_ii_5_raw_long_global"] = ishiura_2019_f9193_ii_5_raw_long_global

ishiura_2019_f9193_ii_5_raw_long_local = """GGCGGCGGCGGCG
GGCGGCGGCCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGGGCGGCGGCGCGCGGCGGCGGCGGCGGCGGCGGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGGCGGCGGCGGCGGCGGCGCGGCGGCGGCGCGGCGGCGGCGGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGGCGGCGGCGGCGGCGGCGGCGGGGGGCGGCGGCGGCGCGGCGGCCGGCGGCGGCGGCG
GCGCGGCGGCGGCGGCGGCGGCGCGCGGCGGCGGCGGCCGGCGGCGGCGGCCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGGCGGCGGCGGGGGCGGCGCGGCGGCGGCGGC""".replace("\n", "")
all_consensuses["ishiura_2019_f9193_ii_5_raw_long_local"] = ishiura_2019_f9193_ii_5_raw_long_local
##----------------------------------------------------------------------------------------------------------




## PODAR
##----------------------------------------------------------------------------------------------------------
## Podar 21073LRa006 long allele:
podar_2023_21073LRa006_long_global = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GCGGCGGCGGCGGCGGCGCGCGGCGGCGGCGGCGGCGGCGGCGCCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
AGCGGCGGCGGCGGCGGCCGC""".replace("\n", "")
all_consensuses["podar_2023_21073LRa006_long_global"] = podar_2023_21073LRa006_long_global

podar_2023_21073LRa006_long_local = """GGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCCTCGGCGGCGGCGC""".replace("\n", "")
all_consensuses["podar_2023_21073LRa006_long_local"] = podar_2023_21073LRa006_long_local

podar_2023_21073LRa006_long_flye = reverse_sequence("""GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCGCGCGCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCC""".replace("\n", ""))
all_consensuses["podar_2023_21073LRa006_long_flye"] = podar_2023_21073LRa006_long_flye


## Podar 21073LRa006 short allele:
podar_2023_21073LRa006_short_global = reverse_sequence("""GCCGCCTCCTCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["podar_2023_21073LRa006_short_global"] = podar_2023_21073LRa006_short_global

podar_2023_21073LRa006_short_local = reverse_sequence("""GCCGCCTCCTCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["podar_2023_21073LRa006_short_local"] = podar_2023_21073LRa006_short_local
##----------------------------------------------------------------------------------------------------------




## TIAN
##----------------------------------------------------------------------------------------------------------
## Tian F1-IV-15 long allele:
tian_2019_f1_iv_15_long_global = """GGGGGGGGGCGGTGGCGCGCTGGCGGTGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCTGGCGGTGGTGGTGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGCGGCGGCGGTGGCAGCGGCGGTGGTGGTTGGTGGTGGTGGTGGTGGCGGTG
TGGCTGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCAAGGAGGAGGCGGCGGCGGAGGCGGCGGCGGAGG
CGGCGGCGGAGGAGGCGGCGGCGGAGGGAGCGCGGGGGGAGGCGGCGGCGAGGAGGCGGC""".replace("\n", "")
all_consensuses["tian_2019_f1_iv_15_long_global"] = tian_2019_f1_iv_15_long_global

tian_2019_f1_iv_15_long_local = """GGGGGGTGGCGGTGGCGCGCTGGCGGTGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGTGGCGGTGGTGGTGGTGGTGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGCGGCGGCGGTGGCAGCGGCGGTGGTGGTTGGTGGTGGTGGTGGTGGCGGT
GTGGCTGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCAAGGAGGAGGCGGCGGCGGAGGCGGCGGCGGAG
GCGGCGGCGGAGGAGGCGGCGGCGGAGGGAGCGCGGGGGGAGGCGGCGGCGAGGAGGCGGC""".replace("\n", "")
all_consensuses["tian_2019_f1_iv_15_long_local"] = tian_2019_f1_iv_15_long_local


## Tian F1-IV-7 long allele:
tian_2019_f1_iv_7_long_global = """GGTGGTGGCGGCGGGTGGCGGCGGTGGCGGTGGCGGCGGTGGCGGCGGTGGCGGTGGTGGCGGTGGTGGTGGTG
GTGGCGGTGGTGGTGGTGGTGGTGGGTGGTGGTGGTGGCGTGGCAGGCGTGGTGGTGGTGGTGGTGGGTGGTGGC
GGCGGGTGGTGGTGGTGGCGGGTGGCGGTGGTGGTGGTGGTGTGGTGGTGGCGGTGGTGTGGCGGCGGTGGAGGG
GCGGGTGGTGTGGAGGTGGGTGTGGTGGAGGAGGTGGTGGTGGAGGTGGTGGTGGAGGAGGGTGGTGGAGGGGTG
GTGGAGGGAGGTGGTGGTGGGAGGGGAGGTGGTGGTGGGAGGGAGGTGGGTGGTGGAGGAGGTGGTGGTGGAGGA
GGTGGTGGTGGAGAGGTGGTGGTGGAGGGAGGTGGTGGTGGAGGGAGGGGTGGTGGTGGAGGAGGTGGCGGGTGG
AGGGAGTGGTGGTGAGGGAGGTGGTGGTGGAGGGAGGTGGCGGGTGGAGGAGGTGGTGGCGGGAGGAGGTGGCGG
TGGAGGAGGTGGCGGCGGGAGGGAGGTGGCGGGTGGTGAGGCGGTGGCCGGAGGAGGTGGCGGCGGAGGAGGCGG
CGGCGGAGGAGGGCGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGC""".replace("\n", "")
all_consensuses["tian_2019_f1_iv_7_long_global"] = tian_2019_f1_iv_7_long_global

tian_2019_f1_iv_7_long_local = """GGTGGTGGCGGCGGGTGGCGGCGGTGGCGGTGGCGGCGGTGGCGGCGGTGGCGGTGGTGGCGGTGGTGGTGGTG
GTGGCGGTGGTGGTGGTGGTGGTGGGTGGTGGTGGTGGCGTGGCAGGCGTGGTGGTGGTGGTGGTGGGTGGTGGC
GGCGGGTGGTGGTGGTGGCGGGTGGCGGTGGTGGTGGTGGTGTGGTGGTGGCGGTGGTGTGGCGGCGGTGGAGGG
GCGGGTGGTGTGGAGGTGGGTGTGGTGGAGGAGGTGGTGGTGGAGGTGGTGGTGGAGGAGGGTGGTGGAGGGGTG
GTGGAGGGAGGTGGTGGTGGGAGGGGAGGTGGTGGTGGGAGGGAGGTGGGTGGTGGAGGAGGTGGTGGTGGAGGA
GGTGGTGGTGGAGAGGTGGTGGTGGAGGGAGGTGGTGGTGGAGGGAGGGGTGGTGGTGGAGGAGGTGGCGGGTGG
AGGGAGTGGTGGTGAGGGAGGTGGTGGTGGAGGGAGGTGGCGGGTGGAGGAGGTGGTGGCGGGAGGAGGTGGCGG
TGGAGGAGGTGGCGGCGGGAGGGAGGTGGCGGGTGGTGAGGCGGTGGCCGGAGGAGGTGGCGGCGGAGGAGGCGG
CGGCGGAGGAGGGCGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGC""".replace("\n", "")
all_consensuses["tian_2019_f1_iv_7_long_local"] = tian_2019_f1_iv_7_long_local


## Tian F2-II-3 long allele:
tian_2019_f2_ii_3_long_global = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGGCGGCGGCGGGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCAGCGGCAGCAGCGGCGGCGGCGGCGGCGGCAGCGGCACGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGGGCGGCGGCGGCGGCGGCGGCAGCGGCGGCGGCGGCGGCAGCGGCAGCAGCGGCGGCGGCG
GCGGAGGGGAGGCAGCGGCGGAGGAGGCGGGAGGAGGAGGCGGCGGGGGAGGGCGGCGGCGGAGGAGGCGTGGCG
GCGGAGGAGGGCGGCGGCGGAGGAGGCGGCGGCGGGGGAGGCGGGGGCGGAGGAGGCGGCGGCGGAGGAGGGCGG
CGGAGGGAGGCGGCGGCGGAGGGCCCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCG
GAGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCAGCGGAGGAG
GCGGCGGCGGAGGAGGCGGCGGCGGGAGGAGGCGGCGGCGGAGGAGAGGAGGCGGCGGCGGAGGAGGCGGC""".replace("\n", "")
all_consensuses["tian_2019_f2_ii_3_long_global"] = tian_2019_f2_ii_3_long_global

tian_2019_f2_ii_3_long_local = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCAGCGGCAGCAGCGGCGGCAGCGGCGGCGGCAGCGGCGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGGGCGGCGGCGGCGGCGGCGAGCGGCGGCGGCGGCGGCAGCGGCAGCAGCGGCGGCGGCGGCGGG
GCGGAGGCAGCGGCGGAGGAGGCGGGAGGAGGAGGCGGCGGGGGAGGGCGGCGGCGGAGGAGGCGTGGCGGCGGA
GGAGGGCGGCGGCGGAGGAGGCGGCGGCGGGGGAGGCGGGGGCGGAGGAGGCGGCGGCGGAGGAGGGCGGCGGAG
GGAGGCGGCGGCGGAGGGCCCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCAGGAGG
GGCGGAGGAGGCGGCGGCGGAGGGGCGGCGGCGGAGGAGGCGGCGGCGGAGGAGGCGGCAGCGGAGGAGGCGGCG
GCGGAGGAGGCGGCGGCGGGAGGAGGCGGCGGCGGAGGAGAGGAGGCGGCGGCGGAGGAGGCGGC""".replace("\n", "")
all_consensuses["tian_2019_f2_ii_3_long_local"] = tian_2019_f2_ii_3_long_local

tian_2019_f2_ii_3_long_flye = reverse_sequence("""GCCGCCTCCTCCGCTCGCCGCCTCCTCCCGC
CGCCGCCTCCTCCGCCGCCGCCTCCTCCAGCCGCCGCCCCCTCCTCCGCCGCCGCCTCCT
CCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCT
CCGCCGCCGCTCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCCTC
CCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCTCCTCCGCCGCCGCCT
CCTCCGCCGCCGCCCTCCTCCGCCGCCAGCCTCCCTCCGCCGCCGCCTCCTCCCGCCGCC
GCCTCCTCCACGCCGCCTCCTCCGCCGCCGCCTCCGCCCCGCCACCGCTGCTGCCGCCGC
TGCTGCCGCTGCCGCCGCCGCCGCCGCTGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGTGCCGCCGCCGCCGCCGCCGCCGCCGCCGCTGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCTGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["tian_2019_f2_ii_3_long_flye"] = tian_2019_f2_ii_3_long_flye


## Tian F4-II-2 long allele:
tian_2019_f4_ii_2_long_global = """GGTGGCGGCGGCG
GGGGGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGGCGGCGGTGGCGGCGGCGGCGGCGGGTGGCGGCGGCGGC
GGCGGCGGTGGCGGCGGCGGCGGCGGCGGCGGTGGTGGCGGCGGCGGCGGTAGCGGCGGCGGCGGTGGCGGCGGC
GGCGGCGGTGGCGGTGGCGGCGGCGGCGGTGGCGGCGGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGTGGCGGCGGCGGCGGCGGCGGCGGCAGTGGCGGCGGCAGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGCGGCGGC""".replace("\n", "")
all_consensuses["tian_2019_f4_ii_2_long_global"] = tian_2019_f4_ii_2_long_global

tian_2019_f4_ii_2_long_local = """GGTGGCGGCGGCGGGGGG
GCGGCGGCGGCGGCGGCGGCGGGGCGGTGGCGGGCGGCGGTGGCGGCGGCGGCGGCGGGTGGCGGCGGCGGCGGC
GGCGGTGGCGGCGGCGGCGGCGGCGGCGGCGGTGGCGGCGGCGGCGGTGGCGGCGGCGGTGGTGGCGGCGGCGGC
GGCGGTGGCGGTGGCGGCGGCGGCGGTGGCGGCGGGCGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGGCGGCGG
CGGCGGCGCGCGGCGGCGGCGGCGGCGGCGGCGGCAGCGGTGGCGGCAGCGGCGGCGGCGGCGGCGGCAGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGC""".replace("\n", "")
all_consensuses["tian_2019_f4_ii_2_long_local"] = tian_2019_f4_ii_2_long_local


## Tian F5-II-1 long allele:
tian_2019_f5_ii_1_long_global = """GGCGGCGGCGGTGGCGGCGGCGGCGGCGGTGGCGTGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGGCGGCGGTGGCGGCGGTGGCGTGGCGGCGGCGGCGG
CGGCGGCGGCGCGGCGGCGGCGGCGGCGGCGGCGGCGGTGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGTGGCGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC""".replace("\n", "")
all_consensuses["tian_2019_f5_ii_1_long_global"] = tian_2019_f5_ii_1_long_global

tian_2019_f5_ii_1_long_local = """GGCGGCGGCGGTGGCGGCGGCGGCGGCGGTGGCGTGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGGCGGCGGTGGCGGCGGTGGCGTGGCGGCGGCGGCGGC
GGCGGCGGCGCGGCGGCGGCGGCGGCGGCGGCGGCGGTGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGTGGCGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC""".replace("\n", "")
all_consensuses["tian_2019_f5_ii_1_long_local"] = tian_2019_f5_ii_1_long_local


## Tian F5-II-4 long allele:
tian_2019_f5_ii_4_long_global = """GGCGGTGGTGGTGGTGGTGGT
GGGTGGGTGGTGGTGGTGGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGGTGGTGGTGGTGGTGGTGGGTG
GGTGGGTGGTGGTGGTGGTGGTGGTGGTGGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGTGGCGGGTGGTGGTG
GGGTGGTGGCGGCGGTGGTGGTGTGGCGGTGGCGGTGGCGGCGGTGGCGGTGGCGGCGGCGGTGGCGGTGGCGGC
GGGTGGCGGCGGCGGCGGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGT""".replace("\n", "")
all_consensuses["tian_2019_f5_ii_4_long_global"] = tian_2019_f5_ii_4_long_global

tian_2019_f5_ii_4_long_local = """GGCGGTGGTGGTGGTGGTGGT
GGGTGGGTGGTGGTGGTGGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGGTGGTGGTGGTGGTGGTGGGTG
GGTGGGTGGTGGTGGTGGTGGTGGTGGTGGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGTGGCGGGTGGTGGTG
GGGTGGTGGCGGCGGTGGTGGTGTGGCGGTGGCGGTGGCGGCGGTGGCGGTGGCGGCGGCGGTGGCGGTGGCGGC
GGGTGGCGGCGGCGGCGGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGT""".replace("\n", "")
all_consensuses["tian_2019_f5_ii_4_long_local"] = tian_2019_f5_ii_4_long_local


## Tian F9-II-6 long allele:
tian_2019_f9_ii_6_long_global = """GGCGGCGGCGGCGGCGGCGGCAGCGGCGGCAGCGGC
GGCGGCGGCGGCGGCGGCGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGCAGCGGCGGCGGCGGCGGCGGCGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCAGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCAGCGGCGGCGGCGGCGGCGGGCGCAGCGGCGGCGGCGGCAGCGGCGGCAGCGGCAGC
GGCGGCGGCAGCAGCGGCAGCGGCGGCGGCGGCGGCGGCGCGGCGGCAGCGGCGGCAGCGGCAGCGGCGGCGGCA
GCGGCGGCGGCGGCGGCAGAGGAGGCGGC""".replace("\n", "")
all_consensuses["tian_2019_f9_ii_6_long_global"] = tian_2019_f9_ii_6_long_global

tian_2019_f9_ii_6_long_local = """GGCGGCGGCGGCGGCGGCGGCAGCGGCGGCAGCG
GCGGCGGCGGCGGCGGCAGCGCGGCGGCGGCGGCGGCAGCGGCGGCGGCGGCGCAGCGGCAGCGGCGGCGGCGGC
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCAGCGGCGGCGGCGGCGGCGGCGGCA
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGCGCGCGCAGCAGCGGCGGCGGCGGCAGCGGCGG
CAGCGGCAGCGGCGGCGGCAGCAGCGGCAGCGGCGGCGGCGGCGGCGGCGCGGCGGCAGCGGCGGCAGCGGCAGC
GGCGGCGGCAGCGGCGGCGGCGGCGGCAGAGGAGGCGGC""".replace("\n", "")
all_consensuses["tian_2019_f9_ii_6_long_local"] = tian_2019_f9_ii_6_long_local

tian_2019_f9_ii_6_long_flye = reverse_sequence("""GCCGCCTTCCTGCCGCCGCCGCCGCCGCCGC
TGCCGCCGCCGCCGCCGCCGCTGCCGCCGCTGCCGCCAGCTGCCGCCGCCGCCGCTGCTG
CCGCCGCCGCCGCCGCTGCCGCTGCCGCTGCCGCCGCTGCCGCTGCCGCCGTTCGCCGCC
GCCGCGCCGCCGCCGCCGCCGCCGCCGCCGCCGTTGCCGCGCGCCGCCGCCGCCGCTGCC
GCTGCCGCCTGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCGCT
GCCGCCGCCGCTGCTGCTGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCTCGCCGC
CGCCGCCGCCGCCGCTGCCGCCGCTGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["tian_2019_f9_ii_6_long_flye"] = tian_2019_f9_ii_6_long_flye
##----------------------------------------------------------------------------------------------------------





## BATCH 2
##----------------------------------------------------------------------------------------------------------
## 20JK4322C short allele:
patient_20JK4322C_short_global = reverse_sequence("""GCCTCCTCCTCCGCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""")
all_consensuses["20JK4322C_short_global"] = patient_20JK4322C_short_global

patient_20JK4322C_short_local = reverse_sequence("""GCCTCCTCCTCCCCGCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCC""".replace("\n", ""))
all_consensuses["20JK4322C_short_local"] = patient_20JK4322C_short_local

patient_20JK4322C_short_flye = reverse_sequence("""GCCGCCTCCTCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["20JK4322_short_flye"] = patient_20JK4322C_short_flye


# 20JO4660C short allele:
patient_20JO4660C_short_global = """GGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGAGGAGG
CGGC""".replace("\n", "")
all_consensuses["20JO4660C_short_global"] = patient_20JO4660C_short_global

patient_20JO4660C_short_local = """GGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGAGGAGGC
GGC""".replace("\n", "")
all_consensuses["20JO4660C_short_local"] = patient_20JO4660C_short_local

patient_20JO4660C_short_flye = reverse_sequence("""GCCGCCTCCTCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["20JO4660C_short_flye"] = patient_20JO4660C_short_flye


# 22PP0924B short allele:
patient_22PP0924B_short_global = """CGCTTTGGCGG
CGGCGGCGGCGGCGGCGGCGGCGGAGGAGGAGGC""".replace("\n", "")
all_consensuses["22PP0924B_short_global"] = patient_22PP0924B_short_global

patient_22PP0924B_short_local = """CGCTTTGGCGGCGGCGGCGGCGGCGGCGGCGGCGGAGGAGGAGGC""".replace("\n", "")
all_consensuses["22PP0924B_short_local"] = patient_22PP0924B_short_local

patient_22PP0924B_short_flye = """GGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGAGGAGGCGGC""".replace("\n", "")
all_consensuses["22PP0924B_short_flye"] = patient_22PP0924B_short_flye


## 22RR5603Q short allele:
patient_22RR5603Q_short_global = """GCAAGTATCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GAGGAGGCGGC""".replace("\n", "")
all_consensuses["22RR5603Q_short_global"] = patient_22RR5603Q_short_global

patient_22RR5603Q_short_local = """GCGGGGCGGCGGCGGCGGCGGCGGCGGCGGCGGAGGAG
GCGGC""".replace("\n", "")
all_consensuses["22RR5603Q_short_local"] = patient_22RR5603Q_short_local

patient_22RR5603Q_short_flye = reverse_sequence("""GCCGCCTCCTCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCC""".replace("\n", ""))
all_consensuses["22RR5603Q_short_flye"] = patient_22RR5603Q_short_flye


## 22RS5734T short allele:
patient_22RS5734T_short_global = reverse_sequence("""GCCTCCTCCTCCCGCCGGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCC""".replace("\n", ""))
all_consensuses["22RS5734T_short_global"] = patient_22RS5734T_short_global

patient_22RS5734T_short_local = reverse_sequence("""GCCTCCTCCTCCCGCCGGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCC""".replace("\n", ""))
all_consensuses["22RS5734T_short_local"] = patient_22RS5734T_short_local

patient_22RS5734T_short_flye = """GGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCAGCGGAGGAGGCGGC""".replace("\n", "")
all_consensuses["22RS5734T_short_flye"] = patient_22RS5734T_short_flye


## GA5817C short allele:
patient_GA5817C_short_global = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGAGGAGGC
GGC""".replace("\n", "")
all_consensuses["GA5817C_short_global"] = patient_GA5817C_short_global

patient_GA5817C_short_local = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
AGGAGGCGGC""".replace("\n", "")
all_consensuses["GA5817C_short_local"] = patient_GA5817C_short_local

patient_GA5817C_short_flye = reverse_sequence("""GCCGCCTCCTCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["GA5817C_short_flye"] = patient_GA5817C_short_flye


## GQ1307H short allele:
patient_GQ1307H_short_global = reverse_sequence("""GCCTCCTCCTCCCGCC
GCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["GQ1307H_short_global"] = patient_GQ1307H_short_global

patient_GQ1307H_short_local = reverse_sequence("""GCCTCCTCCTCCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["GQ1307H_short_local"] = patient_GQ1307H_short_local

patient_GQ1307H_short_flye = reverse_sequence("""GCCGCCTCCTCCGTCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["GQ1307H_short_flye"] = patient_GQ1307H_short_flye
##----------------------------------------------------------------------------------------------------------



## BATCH 3/4 merged
##----------------------------------------------------------------------------------------------------------
## 311 hyper allele:
patient_311_merged_hyper_global = reverse_sequence("""GCCGCCTCCTCC
GCCGCCTCCGCCGCCGCCGCCGCCGCCGCCGCCTCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["311_merged_hyper_global"] = patient_311_merged_hyper_global

patient_311_merged_hyper_local = reverse_sequence("""GCCGCCTCCTCC
GCCGCCTCCGCCGCCGCCGCCGCCGCCGCCGCCTCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["311_merged_hyper_local"] = patient_311_merged_hyper_local


## 311 long allele:
patient_311_merged_long_global = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGAGGAGGCGGCGGAGGAGGCGGC""".replace("\n", "")
all_consensuses["311_merged_long_global"] = patient_311_merged_long_global

patient_311_merged_long_local = """GGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGAGGAGGCGGCGGAGGAGGCGGC""".replace("\n", "")
all_consensuses["311_merged_long_local"] = patient_311_merged_long_local

patient_311_merged_long_flye = reverse_sequence("""GCCGCCTCCTCCGCCGCCTCCTCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["311_merged_long_flye"] = patient_311_merged_long_flye


## 311 short allele:
patient_311_merged_short_global = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGAGGAGGCGGC""".replace("\n", "")
all_consensuses["311_merged_short_global"] = patient_311_merged_short_global

patient_311_merged_short_local = """GGCGG
CGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGAGGAGGCGGC""".replace("\n", "")
all_consensuses["311_merged_short_local"] = patient_311_merged_short_local

patient_311_merged_short_flye = reverse_sequence("""GCCGCCTCCTCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["311_merged_short_flye"] = patient_311_merged_short_flye


## 313 long allele:
patient_313_merged_long_global = reverse_sequence("""GCCGCCTCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["313_merged_long_global"] = patient_313_merged_long_global

patient_313_merged_long_local = reverse_sequence("""GCCGCCTCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["313_merged_long_local"] = patient_313_merged_long_local

patient_313_merged_long_flye = reverse_sequence("""GCCGCCTCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["313_merged_long_flye"] = patient_313_merged_long_flye


## 313 short allele:
patient_313_merged_short_global = reverse_sequence("""GC
CCCTCCTCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCGCCCCCCCC""".replace("\n", ""))
all_consensuses["313_merged_short_global"] = patient_313_merged_short_global

patient_313_merged_short_local = reverse_sequence("""GCCGCCTCCTCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCGCCCCCCCC""".replace("\n", ""))
all_consensuses["313_merged_short_local"] = patient_313_merged_short_local

patient_313_merged_short_flye = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGCGGCGGAGGAGGCGGC""".replace("\n", "")
all_consensuses["313_merged_short_flye"] = patient_313_merged_short_flye


## 317 long allele:
patient_317_merged_long_global = reverse_sequence("""GCCGCCTCCGCCGCCTCCGCCGCCGCCGCCGCCGCCGCCGCCTCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["317_merged_long_global"] = patient_317_merged_long_global

patient_317_merged_long_local = reverse_sequence("""GCCGC
CTCCGCCGCCTCCGCCGCCGCCGCCGCCGCCGCCGCCTCGCGCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["317_merged_long_local"] = patient_317_merged_long_local

patient_317_merged_long_flye = reverse_sequence("""GCCGCCTCCGCCGCCTCCGCCGCCGCCGCCGCCGCCGCCGCCTCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["317_merged_long_flye"] = patient_317_merged_long_flye


## 317 short allele:
patient_317_merged_short_global = """GGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGAGGAGGCGGC""".replace("\n", "")
all_consensuses["317_merged_short_global"] = patient_317_merged_short_global

patient_317_merged_short_local = """GGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGAGGAGGCGGC""".replace("\n", "")
all_consensuses["317_merged_short_local"] = patient_317_merged_short_local


## 318 hyper allele:
patient_318_merged_hyper_global = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCC
GCGGCGGCGGCGGCGGCGGCGGCGGCCGCCGCCGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGCGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCAGGCGGCGC
CGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCGCGCGCGCGCGCGCGCGCGCG
CGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGC
GCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCG
CGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGGCGGCGACGGCGCCG
GCGCCGGCGGCGGCGCCGGCGGCGGCGGCGGCGGCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCG
CCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGACGCCGGCGCCGGCGCCGGCGCCG
GCGCCGGCGCCGGCGCCGGCGCCGACGCCGACGCCGACGCCGACGCCGACGCCGACGCCGCCGCCGCCGACGCCG
ACGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCG
CCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCG
GCGCCGGCGCCGGCGCCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGACGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGCGG
AGGCGGC""".replace("\n", "")
all_consensuses["318_merged_hyper_global"] = patient_318_merged_hyper_global

patient_318_merged_hyper_local = """GGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCCGCGGCGGCGGCGGCGGCGGCGGCGGCCGCCGCCGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCAGCGGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGG
CGCCGGCGCGGCGGCGACGGCGCCGGCGCCGGCGGCGGCGCCGGCGGCGGCGGCGGCGGCGGCGCCGGCGCCGGC
GCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCC
GACGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGACGCCGACGCCGACGCCGACGCCGAC
GCCGACGCCGCCGCCGCCGACGCCGACGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGC
GCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCC
GGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGACGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCG
CGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGC
GCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCG
CGCGCGCGCGCGCGCGCGCGCGCGCGGCGCGGAGGCGGC""".replace("\n", "")
all_consensuses["318_merged_hyper_local"] = patient_318_merged_hyper_local


## 318 long allele:
patient_318_merged_long_global = reverse_sequence("""GCCGCCTCCGCCGCCTCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["318_merged_long_global"] = patient_318_merged_long_global

patient_318_merged_long_local = reverse_sequence("""GCCGCCTCCGCCG
CCTCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["318_merged_long_local"] = patient_318_merged_long_local

patient_318_merged_long_flye = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGAGGCGGCGGAGGCGGC""".replace("\n", "")
all_consensuses["318_merged_long_flye"] = patient_318_merged_long_flye


## 318 short allele:
patient_318_merged_short_global = reverse_sequence("""GCCGCCTCCTGCCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["318_merged_short_global"] = patient_318_merged_short_global

patient_318_merged_short_local = reverse_sequence("""GCCGCCTCCTGCCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""")
all_consensuses["318_merged_short_local"] = patient_318_merged_short_local

patient_318_merged_short_flye = reverse_sequence("""GCCGCCTCCTCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["318_merged_short_flye"] = patient_318_merged_short_flye


## 319 long allele:
patient_319_merged_long_global = reverse_sequence("""GCCGCCTCCTCCGCCGC
CGCCGCCGTCTTCTCCGCCGCCGCCGCCGCCTCCTCCGCCGCCGCCGCCGCCGCCGCCGCCGCCTCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCTCCGCCGCCGCCGCCGCCGCCGCCGCCTCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["319_merged_long_global"] = patient_319_merged_long_global

patient_319_merged_long_local = reverse_sequence("""GCCGCCTCCTCCGCCGCCGCCGCCGTCTTCTCCGCCGCCGCCGCCGCCTCC
TCCGCCGCCGCCGCCGCCGCCGCCGCCGCCTCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCTCCGCCGCCGCCGCCGCCGCCGCCGCCTCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCC""".replace("\n", ""))
all_consensuses["319_merged_long_local"] = patient_319_merged_long_local

patient_319_merged_long_flye = reverse_sequence("""GCCGCCTCCTCCGCCGCCGCCGCCGCCTCCTCCGCCGCCGCCGCCGCCTCCTCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCTCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCTCCGCCGCCGCCGCCGCCGCCGCCGCCTGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["319_merged_long_flye"] = patient_319_merged_long_flye


## 319 short allele:
patient_319_merged_short_global = reverse_sequence("""GCCGCCTCCTCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["319_merged_short_global"] = patient_319_merged_short_global

patient_319_merged_short_local = reverse_sequence("""GC
CGCCTCCTCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["319_merged_short_local"] = patient_319_merged_short_local

patient_319_merged_short_flye = reverse_sequence("""GCCGCCTCCTCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["319_merged_short_flye"] = patient_319_merged_short_flye


## 327 hyper allele:
patient_327_merged_hyper_global = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCGGCCGCGGCGGCGGCGC
GGCCGCGGCCGCGGCCGCGGCCGCGGCGGCCGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCCGCCGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGCGCGCGCGCGCGCGCG
CGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCCGCGCGCGCGCGCGCGCGCGCGCGCG
CGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGC
GCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCGGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCGCGGCCGCGGCCGCGGCCGCGGCCGCCGCGGCCGCGGCCGCGGCCGCG
GCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCC
GCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGAGGCGGC""".replace("\n", "")
all_consensuses["327_merged_hyper_global"] = patient_327_merged_hyper_global

patient_327_merged_hyper_local = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCG
GCGGCCGCGGCGGCGGCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCGGCCGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGCGGCGCGGCGGGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGCGGCGGCGGCGGCGGCGGCGGCGGCGCCGGCGCGACGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGACGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGC
GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCCGCGCC
GGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGC
GCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCC
GGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCGCCCGCGCCCGCGCCCGCGCCCGCGCCCGCGCCG
CCCGCGCCCGCGCCCGCGCCCGCGCCCGCGCCCGCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCGCCGGCG
CCGCCGCCGCCGCCGCCGCCGCCGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCG
CGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGG
CCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCCGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGG
CGGCGGCGGCGGCGGCGGCGGCGGCGGCGGAGGCGGC""".replace("\n", "")
all_consensuses["327_merged_hyper_local"] = patient_327_merged_hyper_local

patient_327_merged_hyper_flye = """GGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGACGGCCGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCGGCG
GCGGCGGCGGCGGAGGCGGCGGCGGCGGCGGCGGCGGCGGAGGCGGCGGAGGCGGC""".replace("\n", "")
all_consensuses["327_merged_hyper_flye"] = patient_327_merged_hyper_flye


## 327 long allele
patient_327_merged_long_global = reverse_sequence("""GCCGCCTCCGCCGCCTCCCCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["327_merged_long_global"] = patient_327_merged_long_global

patient_327_merged_long_local = reverse_sequence("""GCCGCCTCCGCCGCCTCCCCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC
CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["327_merged_long_local"] = patient_327_merged_long_local


## 327 short allele:
patient_327_merged_short_global = reverse_sequence("""GCCGCCTCCTCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["327_merged_short_global"] = patient_327_merged_short_global

patient_327_merged_short_local = reverse_sequence("""GCCGCCTCCTCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["327_merged_short_local"] = patient_327_merged_short_local

patient_327_merged_short_flye = reverse_sequence("""GCCGCCTCCTCCGCCGCC
GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC
GCCGCCGCCGCCGCCGCC""".replace("\n", ""))
all_consensuses["327_merged_short_flye"] = patient_327_merged_short_flye
##----------------------------------------------------------------------------------------------------------




## Write output to csv
output_file = open("intermediate_files/python_consensuses_pipeline.csv", "w")
output_file.write("consensus_id,sequence\n")
for consensus_id in all_consensuses.keys():
    sequence_content = all_consensuses[consensus_id]
    output_file.write(consensus_id + "," + sequence_content + "\n")
output_file.close()
